version: "3.8"
services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: player
      POSTGRES_PASSWORD: player
      POSTGRES_DB: player
    ports:
      - "5430:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: